### PR TITLE
ci: add all go release lines into the builds

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by chenrui333** [comment]
homebrew shipped [the release build](https://github.com/Homebrew/homebrew-core/pull/65767) against go1.15

**Review by Jankyboy — APPROVED** [review]

**Review by Jankyboy — APPROVED** [review]

**Comment by chenrui333** [comment]
gentle ping @tyndyll

**Review by gedge — APPROVED** [review]
thanks, another for 1.17 would be nice 😉

**Comment by gedge** [comment]
actually, this looks like too many versions to support - do we need all these?

**Pull request closed without merging**
