### PR TITLE
Update MailHog-UI assets vendor

### PR DESCRIPTION
**Pull request by sdurrheimer**
This will among other things import the fix for https://github.com/mailhog/MailHog-UI/pull/22

### CODE REVIEW

**Comment by sdurrheimer** [comment]
@ian-kent Is this project still maintained ?

**Comment by ian-kent** [comment]
@sdurrheimer yeah, just not as actively as I'd like 😞  i'll try and have a look this week

**Comment by ian-kent** [comment]
thanks @sdurrheimer, sorry it took so long!

**Comment by sdurrheimer** [comment]
Thank you

**Pull request merged**
